### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by GLYASAI** [fanux/sealos#163]
```
[root@k8s-1 ~]# sealos init --passwd 123456
2019-12-17 02:30:48 [INFO] [github.com/fanux/sealos/install/print.go:13]
[globals]sealos config is:  {"Hosts":[]}
2019-12-17 02:30:48 [DEBG] [github.com/fanux/sealos/install/print.go:20] ==>SendPackage
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fanux/sealos/install.(*SealosInstaller).KubeadmConfigInstall(0xc00000f380)
	/go/src/github.com/fanux/sealos/install/init.go:53 +0x22a
github.com/fanux/sealos/install.BuildInit()
	/go/src/github.com/fanux/sealos/install/init.go:20 +0x1e3
github.com/fanux/sealos/cmd.glob..func3(0xdc7380, 0xc00000f2c0, 0x0, 0x2)
	/go/src/github.com/fanux/sealos/cmd/init.go:28 +0x22
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).execute(0xdc7380, 0xc00000f2a0, 0x2, 0x2, 0xdc7380, 0xc00000f2a0)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xdc7aa0, 0xc000103f68, 0x87f3be, 0xdc7aa0)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:800
github.com/fanux/sealos/cmd.Execute()
	/go/src/github.com/fanux/sealos/cmd/root.go:46 +0x32
main.main()
	/go/src/github.com/fanux/sealos/main.go:22 +0x20
```

代码不严谨, 没做参数验证. 我漏填了 --master 参数, 直接 panic了. 我想这里应该有参数的验证, 会相应的提示

**Comment by fanux** [comment]
感谢建议, 需要有检查~

**Comment by cuisongliu** [comment]
已经修复 #165
