### ISSUE TITLE
sealos创建k8s 1.18集群，在集群内解释不了内部命名空间等地址

### ISSUE THREAD

**Issue by ckgmg** [fanux/sealos#361]
比如在容器里
nslookup kube-dns.kube-system.svc.cluster.local不出IP，提示找不到

**Comment by fanux** [comment]
1. 用的busybox测试的？如果是换成其它
2. 检查跨主机pod联通性

**Comment by zhangguanzhang** [comment]
time curl -I 10.96.0.10:9153看看

**Comment by ckgmg** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      restartPolicy: Always
      containers:
      - name: busybox
        command:
        - sleep
        - "3600"
        image: busybox:1.28.4
用busybox测试

9153跟53 区别吗

**Comment by ckgmg** [comment]
[root@i22 test]# time curl -I 10.96.0.10:9153
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 27 May 2020 12:59:30 GMT
Content-Length: 19


real	0m0.012s
user	0m0.004s
sys	0m0.006s

**Comment by ckgmg** [comment]
[root@i1 test]# time curl -I 10.96.0.10:53
curl: (52) Empty reply from server

real	0m2.014s
user	0m0.007s
sys	0m0.005s

**Comment by zhangguanzhang** [comment]
9153是metrics的http接口的端口

**Comment by fanux** [comment]
别用busybox，busybox nslookup有bug

**Comment by FrelDX** [comment]
在容器中解析不了 svc的地址啊 用这个安装的

**Comment by fanux** [comment]
coreDNS所在机器的/etc/resolve发出来看下

**Comment by oldthreefeng** [comment]
在容器中解析不了 svc的地址啊.... 集群重启了一次...

$  curl -I 10.96.0.10:53
curl: (7) Failed connect to 10.96.0.10:53; No route to host

coreDNS所在机器的
$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 114.114.114.114

**Comment by zhangguanzhang** [comment]
你在群里吗，我远程看看

**Comment by zhangguanzhang** [comment]
centos的内核的低，会触发1.18+的kube-proxy的那个pareIP的错误，我看ipvs的规则没更新，切了下kube-proxy到1.17.6就行了
```
kubectl -n kube-system set image daemonset/kube-proxy *=registry.aliyuncs.com/k8sxio/kube-proxy:v1.17.6
```

**Comment by oldthreefeng** [comment]
@zhangguanzhang  大佬牛皮.  解决问题的思路清晰... ~~~ 学习了

**Comment by FrelDX** [comment]
我用kubeadm重新装了集群就好了，所有主键也是1.18的。

**Comment by oldthreefeng** [comment]
@FrelDX  我集群有一次停电重启了, 然后就出现了这个问题.   
```
E0610 04:19:01.916711       1 proxier.go:1192] Failed to sync endpoint for service: 10.96.0.1:443/TCP, err: parseIP Error ip=[192 168 0 31 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:01.916789       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[100 70 101 165 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:01.916808       1 proxier.go:1192] Failed to sync endpoint for service: 10.103.137.114:80/TCP, err: parseIP Error ip=[100 70 101 165 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:01.916881       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[100 116 59 71 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:01.916899       1 proxier.go:1192] Failed to sync endpoint for service: 10.96.0.10:53/UDP, err: parseIP Error ip=[100 116 59 71 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:01.916982       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[192 168 0 30 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:01.917000       1 proxier.go:1192] Failed to sync endpoint for service: 10.110.140.83:443/TCP, err: parseIP Error ip=[192 168 0 30 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:31.965080       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[100 70 101 162 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:31.965114       1 proxier.go:1192] Failed to sync endpoint for service: 10.109.196.2:8082/TCP, err: parseIP Error ip=[100 70 101 162 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:31.965215       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[100 70 101 163 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:31.965235       1 proxier.go:1192] Failed to sync endpoint for service: 10.99.176.38:8080/TCP, err: parseIP Error ip=[100 70 101 163 0 0 0 0 0 0 0 0 0 0 0 0]^C
E0610 04:19:31.965359       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[100 74 166 76 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:31.965384       1 proxier.go:1192] Failed to sync endpoint for service: 10.107.12.86:80/TCP, err: parseIP Error ip=[100 74 166 76 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:31.965481       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[100 70 101 157 0 0 0 0 0 0 0 0 0 0 0 0]
E0610 04:19:31.965505       1 proxier.go:1192] Failed to sync endpoint for service: 10.110.119.128:8081/TCP, err: parseIP Error ip=[100 70 101 157 0 0 0 0 0 0 0 0 0 0 0 0]
```
这个是kube-proxy报错内容...  ,然后张馆长帮我替换了镜像就好了.

**Comment by MrCookie0313** [comment]
当服务端pod重建后，客户端通过grpc调过命名空间调用（k8s分配的域名），出现大概20分钟左右路由还是之前pod的路由一直出现服务调不通现象，后面请求grpc域名dns路由就是更新之后的pod的ip，然后就一直可以调用成功，就每次服务端更新pod后出现很长时间调不通的现象，大家有什么好的建议吗

**Comment by FrelDX** [comment]
> 当服务端pod重建后，客户端通过grpc调过命名空间调用（k8s分配的域名），出现大概20分钟左右路由还是之前pod的路由一直出现服务调不通现象，后面请求grpc域名dns路由就是更新之后的pod的ip，然后就一直可以调用成功，就每次服务端更新pod后出现很长时间调不通的现象，大家有什么好的建议吗

kubectl -n kube-system set image daemonset/kube-proxy *=registry.aliyuncs.com/k8sxio/kube-proxy:v1.17.6
执行这个命令

**Comment by oldthreefeng** [comment]
具体问题具体分析....  
如果是kubernetes1.18.0. 建议升级内核, 或者升级kubernetes集群, 或者@FrelDX 的这条命令都可以. @MrCookie0313

**Comment by MrCookie0313** [comment]
这个是应该kube-proxy版本问题吗？还有说是centos内核问题

**Comment by MrCookie0313** [comment]
为什么会出现20分钟很长时间内pod内域名解析还是删除之前pod的ip，但是新的pod其实在容器外也是可以解析到最新podDNS ip

**Comment by MrCookie0313** [comment]
> > 当服务端pod重建后，客户端通过grpc调过命名空间调用（k8s分配的域名），出现大概20分钟左右路由还是之前pod的路由一直出现服务调不通现象，后面请求grpc域名dns路由就是更新之后的pod的ip，然后就一直可以调用成功，就每次服务端更新pod后出现很长时间调不通的现象，大家有什么好的建议吗
> 
> kubectl -n kube-system set image daemonset/kube-proxy *=registry.aliyuncs.com/k8sxio/kube-proxy:v1.17.6
> 执行这个命令

我是同一个命名空间的pod服务间调用，用的是k8s命名空间调用的也行吗

**Comment by oldthreefeng** [comment]
> 为什么会出现20分钟很长时间内pod内域名解析还是删除之前pod的ip，但是新的pod其实在容器外也是可以解析到最新podDNS ip

这个应该是kubernetes1.18.0 版本的和低内核版本不兼容的bug.  PraseIP错误, 详情可以google.

**Comment by MrCookie0313** [comment]
> > 为什么会出现20分钟很长时间内pod内域名解析还是删除之前pod的ip，但是新的pod其实在容器外也是可以解析到最新podDNS ip
> 
> 这个应该是kubernetes1.18.0 版本的和低内核版本不兼容的bug. PraseIP错误, 详情可以google.

但是我们的环境用的是kubernetes1.13.2版本，那就不应该了呀

**Comment by MrCookie0313** [comment]
> 你在群里吗，我远程看看
我们的环境是1.13.2,也可以用这个命令吗

**Comment by FrelDX** [comment]
为什么 用官方的kubeadm装没有问题呢？

**Comment by FrelDX** [comment]
我用官方的工具装完后没有问题，镜像也是1.18的
    Image:         registry.aliyuncs.com/google_containers/kube-proxy:v1.18.2

**Comment by MrCookie0313** [comment]
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: casino-table-extract-service.default.svc.cluster.local/10.96.128.185:50051
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_192]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_192]
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	... 1 more
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_192]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_192]
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	... 1 more
这是当时grpc调用失败的日志，不知道grpc框架有没有做域名dns解析结果做缓存
