### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by binggouxsm** [fanux/sealos#376]
sealos init 安装成功三个master集群之后，执行join命令加入一个节点，命令如下（隐去IP地址和密码用xx代替）
sealos join --node xx.xx.xx.xx --passwd xxxxxxx --pkg-url /root/kube1.16.0.tar.gz

执行结果报错：
```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/fanux/sealos/install.(*SealosInstaller).GeneratorToken(0xc00000f3e0)
        /go/src/github.com/fanux/sealos/install/join.go:22 +0x89
github.com/fanux/sealos/install.BuildJoin()
        /go/src/github.com/fanux/sealos/install/join.go:15 +0xd0
github.com/fanux/sealos/cmd.glob..func5(0xda37a0, 0xc00006c6c0, 0x0, 0x6)
        /go/src/github.com/fanux/sealos/cmd/join.go:29 +0x20
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).execute(0xda37a0, 0xc00006c600, 0x6, 0x6, 0xda37a0, 0xc00006c600)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xda3a00, 0x9703c1, 0x17, 0x1)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:800
github.com/fanux/sealos/cmd.Execute()
        /go/src/github.com/fanux/sealos/cmd/root.go:46 +0x32
main.main()
        /go/src/github.com/fanux/sealos/main.go:20 +0x20
```

**运行环境**
- Docker版本:    19.03
- Kubernetes版本 : kube1.16.0.tar.gz
- sealos版本: 未知，kube1.16.0.tar.gz包中bin目录下sealos，大小13.2M左右大小，不包含version命令
- 操作系统:  redhat 7.7

**Comment by PatHoo** [comment]
试试`kube1.18.0.tar.gz`版本，离线包与sealos版本得配合使用，最近重构动作大。

**Comment by binggouxsm** [comment]
用的是kube1.16.0.tar.gz包中包含的sealos，应该是配合的老版本的sealos，连最新的version命令都没有包含，版本号都不知道哪个版本。

**Comment by fanux** [comment]
1.16.0测试版，建议升级小版本 sealos务必使用3.3.7
