### ISSUE TITLE
在增加master和node节点的时候报错

### ISSUE THREAD

**Issue by guolichengzlc** [fanux/sealos#584]
```
Loaded image: fanux/lvscare:latest
  WARNING: You're not using the default seccomp profile
driver is systemd

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fanux/sealos/install.(*SealosInstaller).GeneratorCerts(0xc00026c9b0)
        /go/src/github.com/fanux/sealos/install/join.go:57 +0x179
github.com/fanux/sealos/install.joinMastersFunc(0xc000271370, 0x1, 0x1)
        /go/src/github.com/fanux/sealos/install/join.go:29 +0x1c3
github.com/fanux/sealos/install.BuildJoin(0xc000271370, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/fanux/sealos/install/join.go:12 +0x77
github.com/fanux/sealos/cmd.glob..func6(0x2ce6840, 0xc0001ed160, 0x0, 0x2)
        /go/src/github.com/fanux/sealos/cmd/join.go:34 +0x118
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).execute(0x2ce6840, 0xc0001ed120, 0x2, 0x2, 0x2ce6840, 0xc0001ed120)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2ce6ac0, 0xc000125f68, 0x13e3d4e, 0x2ce6ac0)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:864
github.com/fanux/sealos/cmd.Execute()
        /go/src/github.com/fanux/sealos/cmd/root.go:46 +0x32
main.main()
        /go/src/github.com/fanux/sealos/main.go:22 +0x20
```
添加node和master时候报错，我用clean以后，删除要加入节点所有安装的东西还是报错

**Comment by oldthreefeng** [comment]
@guolichengzlc  麻烦写清楚更多信息.. 比如基础环境. 安装版本

**Comment by guolichengzlc** [comment]
基础环境 CentOS Linux release 7.9.2009 ，安装版本kube1.17.0

**Comment by guolichengzlc** [comment]
发现coredns报错1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused

**Comment by oldthreefeng** [comment]
在群里么? @guolichengzlc  我远程看看.

**Comment by guolichengzlc** [comment]
提过申请，但是未通过

**Comment by oldthreefeng** [comment]
麻烦再提交一下 98488045

**Comment by oldthreefeng** [comment]
经过远程发现是 低版本的 `.sealos `文件被删除, 并且版本管理混乱。  已经处理了
