### ISSUE TITLE
免密报错

### ISSUE THREAD

**Issue by currycan** [fanux/sealos#90]
2019-09-02 14:34:35 [EROR] [github.com/fanux/sealos/install/utils.go:89]        Error create ssh session failed ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

ssh 创建的密钥对算法是：Ed25519 ，貌似不支持

**Comment by cuisongliu** [comment]
请附上 执行命令以及错误堆栈信息。

**Comment by fanux** [comment]
是不是各服务器密码不一样？  用--passwd服务器密码必须都一样，否则请用密钥

**Comment by currycan** [comment]
执行命令：
```shell
sealos init --master 10.88.88.1 \
    --master 10.88.88.2 \
    --master 10.88.88.3 \
    --node 10.88.88.4 \
    --node 10.88.88.5 \
    --node 10.88.88.6 \
    --user root \
    --pk /root/.ssh/id_ed25519 \
    --version v1.15.0 \
    --pkg-url /root/kube1.15.0.tar.gz
```
报错：
```
2019-09-03 09:03:31 [INFO] [github.com/fanux/sealos/install/utils.go:83] 10.88.88.2      ls -l /root | grep kube1.15.0.tar.gz | wc -l
2019-09-03 09:03:33 [EROR] [github.com/fanux/sealos/install/utils.go:89]        Error create ssh session failed ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
panic: 1

goroutine 9 [running]:
github.com/fanux/sealos/install.Cmd(0xc000022990, 0xb, 0xc000024960, 0x2c, 0x0, 0x0, 0x0)
        /go/src/github.com/fanux/sealos/install/utils.go:90 +0x4ba
github.com/fanux/sealos/install.RemoteFilExist(0xc000022990, 0xb, 0xc000020900, 0x17, 0x0)
        /go/src/github.com/fanux/sealos/install/utils.go:109 +0x1a7
github.com/fanux/sealos/install.SendPackage.func1(0xc000022bc0, 0xc000020900, 0x17, 0xc00002c0c0, 0x36, 0x100, 0x7fffd10856ed, 0x17, 0xc00002e6e0, 0x43, ...)
        /go/src/github.com/fanux/sealos/install/utils.go:292 +0xb0
created by github.com/fanux/sealos/install.SendPackage
        /go/src/github.com/fanux/sealos/install/utils.go:289 +0x56f
[root@k8s-master-01 ~]# ansible all -m ping
10.88.88.3 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
10.88.88.5 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
10.88.88.2 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
10.88.88.1 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
10.88.88.4 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
10.88.88.6 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
````

**Comment by fanux** [comment]
sealos 哪个版本的？ https://github.com/fanux/sealos/releases/download/v2.0.5-alpha.1/sealos 试下这个版本

**Comment by currycan** [comment]
就是用的这个版本，刚刚试了下还不不行，用口令是可以的。

**Comment by cuisongliu** [comment]
@currycan  你重新试一下最新版，我加了测试ssh的方法。感觉还是ssh没上去。你再看一下。

**Comment by fanux** [comment]
先关了，有问题reopen

**Comment by currycan** [comment]
抱歉现在才回复，已经验证过了。现在没问题了，谢谢！
